export function buildMachineGuides({ metadata, endpoints, recordEndpoints, absoluteUrl }) {
  const counts = metadata.record_counts;

  const llms = `# Bridge Incident Registry\n\nBridge Incident Registry is a historical, evidence-based registry of cross-chain bridge and interoperability incidents and their aftermath.\n\nIt is not a real-time exploit alert, a bridge safety ranking, a recommendation service, or investment guidance.\n\nCanonical origin: ${metadata.canonical_origin}\nGenerated at: ${metadata.generated_at}\nLatest verified record date: ${metadata.latest_verified_at ?? "unknown"}\nSchema version: ${metadata.schema_version}\nCanonical reviewed records only: true\n\nCurrent record counts:\n- Bridges: ${counts.bridges}\n- Incidents: ${counts.incidents}\n- Events: ${counts.events}\n- Evidence: ${counts.evidence}\n\nMachine-readable entry points:\n- Version: ${endpoints.version}\n- Manifest: ${endpoints.manifest}\n- Bridges: ${endpoints.bridges}\n- Incidents: ${endpoints.incidents}\n- Events: ${endpoints.events}\n- Evidence: ${endpoints.evidence}\n- Chain references: ${endpoints.chains}\n- Asset references: ${endpoints.assets}\n\nPer-record JSON patterns:\n- Bridge dossier: ${recordEndpoints.bridge}\n- Incident dossier: ${recordEndpoints.incident}\n\nHuman canonical pages:\n- Bridge: ${absoluteUrl("/bridge/{slug}/")}\n- Incident: ${absoluteUrl("/incident/{slug}/")}\n\nInterpretation notes:\n- confidence records the strength of a reviewed claim.\n- last_verified_at records when a bridge or incident was last checked.\n- loss, recovery, return, reimbursement, freezing, minting, and burning remain distinct concepts.\n- record dossiers are derived from the same reviewed canonical datasets as the aggregate files.\n- public files contain reviewed canonical records only.\n`;

  const ai = `Bridge Incident Registry canonical data guide\n\nUse ${endpoints.manifest} as the machine-readable entry point.\nUse ${endpoints.version} for schema, generated time, verification marker, and record counts.\n\nPrimary dataset: ${endpoints.bridges}\nSupporting datasets:\n- ${endpoints.incidents}\n- ${endpoints.events}\n- ${endpoints.evidence}\n\nPer-record reviewed dossiers:\n- Bridge: ${recordEndpoints.bridge}\n- Incident: ${recordEndpoints.incident}\n\nHuman bridge pages follow ${absoluteUrl("/bridge/{slug}/")}\nHuman incident pages follow ${absoluteUrl("/incident/{slug}/")}\n\nThis registry is historical and informational. Inclusion, status, and incident counts are not a current safety ranking or recommendation.\n`;

  return { llms, ai };
}
