import fs from "node:fs";
const read=(n)=>JSON.parse(fs.readFileSync(`data/${n}.json`,"utf8"));
const write=(n,r)=>fs.writeFileSync(`data/${n}.json`,`[\n${r.map(x=>`  ${JSON.stringify(x)}`).join(",\n")}\n]\n`);
const bridges=read("bridges"),incidents=read("incidents"),events=read("events"),evidence=read("evidence");
const get=(a,id)=>{const x=a.find(v=>v.id===id);if(!x)throw new Error(`missing ${id}`);return x};
Object.assign(get(bridges,"bir_bridge_000004"),{last_reviewed_at:"2026-06-15",last_verified_at:"2026-06-15"});
Object.assign(get(incidents,"bir_inc_000004"),{source_count:7,last_reviewed_at:"2026-06-15",last_verified_at:"2026-06-15",reimbursement_status:"in_progress",postmortem_available:"partial",unresolved_reason:["Recovery and buyback activity remains ongoing and does not establish full reimbursement.","The final recovered amount and completion date remain unknown."],known_unknowns:["The total amount repurchased, burned, or returned remains incomplete.","The recovery program requires later outcome review."]});
const addedEvents=[
{"id":"bir_ev_000050","bridge_id":"bir_bridge_000004","incident_id":"bir_inc_000004","event_type":"recovery_program_documented","event_date":"2023-03","event_date_precision":"month","title":"Harmony documented treasury-led recovery activity","description":"Harmony reported using treasury funds to recover and burn depegged assets while community recovery work continued.","confidence":"high","record_maturity":"reviewed","update_status":"current","impact_level":"major","status_effect":"recovery program in progress","source_count":1,"sort_order":30,"amount_text":null,"recovered_amount_text":"partial buyback and burn activity reported","reimbursement_status":"in_progress","restart_status":"not_reopened","affected_chains":["harmony","ethereum","bnb-chain"],"affected_assets":["eth","usdc","usdt","wbtc","bnb","one"],"notes":null,"duplicate_of":null,"merged_into":null},
{"id":"bir_ev_000051","bridge_id":"bir_bridge_000004","incident_id":"bir_inc_000004","event_type":"recovery_partner_expansion","event_date":"2025-06-17","event_date_precision":"day","title":"Additional Harmony recovery partner proposed","description":"A community proposal described continued buyback-and-burn recovery work and sought recognition as an additional recovery partner.","confidence":"medium","record_maturity":"reviewed","update_status":"current","impact_level":"major","status_effect":"ongoing recovery framework expanded","source_count":1,"sort_order":40,"amount_text":null,"recovered_amount_text":"ongoing buyback and burn activity","reimbursement_status":"in_progress","restart_status":"not_reopened","affected_chains":["harmony","ethereum","bnb-chain"],"affected_assets":["eth","usdc","usdt","wbtc","bnb","one"],"notes":"Evidence of continuing recovery activity, not full reimbursement.","duplicate_of":null,"merged_into":null}
];
for(const x of addedEvents){if(events.some(v=>v.id===x.id))throw new Error(`duplicate ${x.id}`);events.push(x)}
const addedSources=[
{"id":"bir_src_000068","bridge_id":"bir_bridge_000004","incident_id":"bir_inc_000004","event_id":"bir_ev_000010","source_type":"official_statement","title":"Summary of the Horizon Bridge Incident","url":"https://talk.harmony.one/t/summary-of-the-horizon-bridge-incident/20990","publisher":"Harmony","published_at":"2022-08-24","published_at_precision":"day","reliability":"high","source_tier":"tier_1","url_status":"live","accessed_at":"2026-06-15","claim_scope":"incident_case","language":"en","author":"Harmony Team","quote_excerpt":null,"is_primary":true,"is_paywalled":false,"is_official_domain":true,"supports_amount":true,"supports_recovery":true,"supports_reimbursement":false,"supports_reopen":false,"supports_shutdown":true,"supports_migration":false,"notes":"Official incident and response summary."},
{"id":"bir_src_000069","bridge_id":"bir_bridge_000004","incident_id":"bir_inc_000004","event_id":"bir_ev_000050","source_type":"official_blog","title":"State of Harmony Q1 2023","url":"https://blog.harmony.one/p/state-of-harmony-q1-2023","publisher":"Harmony","published_at":"2023-03-31","published_at_precision":"day","reliability":"high","source_tier":"tier_1","url_status":"live","accessed_at":"2026-06-15","claim_scope":"recovery","language":"en","author":"Harmony","quote_excerpt":null,"is_primary":true,"is_paywalled":false,"is_official_domain":true,"supports_amount":false,"supports_recovery":true,"supports_reimbursement":true,"supports_reopen":false,"supports_shutdown":false,"supports_migration":false,"notes":"Official update describing treasury-funded recovery and burn activity."},
{"id":"bir_src_000070","bridge_id":"bir_bridge_000004","incident_id":"bir_inc_000004","event_id":"bir_ev_000051","source_type":"community_reference","title":"Proposal: UtilityDAO — Recovery Partner for Harmony Protocol","url":"https://talk.harmony.one/t/proposal-utilitydao-recovery-partner-for-harmony-protocol/26467","publisher":"Harmony Community Forum","published_at":"2025-06-17","published_at_precision":"day","reliability":"medium","source_tier":"tier_2","url_status":"live","accessed_at":"2026-06-15","claim_scope":"recovery","language":"en","author":"UtilityDAO","quote_excerpt":null,"is_primary":false,"is_paywalled":false,"is_official_domain":true,"supports_amount":false,"supports_recovery":true,"supports_reimbursement":true,"supports_reopen":false,"supports_shutdown":false,"supports_migration":false,"notes":"Evidence that community recovery work remained active in 2025."}
];
for(const x of addedSources){if(evidence.some(v=>v.id===x.id))throw new Error(`duplicate ${x.id}`);evidence.push(x)}
write("bridges",bridges);write("incidents",incidents);write("events",events);write("evidence",evidence);
