import fs from "node:fs";
const read=(n)=>JSON.parse(fs.readFileSync(`data/${n}.json`,"utf8"));
const write=(n,r)=>fs.writeFileSync(`data/${n}.json`,`[\n${r.map(x=>`  ${JSON.stringify(x)}`).join(",\n")}\n]\n`);
const bridges=read("bridges"),incidents=read("incidents"),events=read("events"),evidence=read("evidence");
const get=(a,id)=>{const x=a.find(v=>v.id===id);if(!x)throw new Error(`missing ${id}`);return x};
Object.assign(get(bridges,"bir_bridge_000003"),{status:"limited",summary:"Nomad Bridge suffered a message-verification exploit in August 2022 and later relaunched a restricted recovery-oriented bridge flow. New canonical-token deposits remained disabled while affected users could bridge back assets and access pro-rata recovered funds.",last_reviewed_at:"2026-06-15",last_verified_at:"2026-06-15",end_date:null,end_date_precision:"unknown",terminal_reason:null,official_url_status:"live",notes:"Classified as limited because the official recovery bridge relaunched while unrestricted new deposits remained disabled."});
Object.assign(get(incidents,"bir_inc_000003"),{source_count:7,last_reviewed_at:"2026-06-15",last_verified_at:"2026-06-15",reimbursement_status:"in_progress",restart_status:"partially_reopened",current_outcome:"limited_after_incident",postmortem_available:"full",unresolved_reason:["Only a pro-rata share of recovered assets was made available through the recovery bridge.","Final recovery and reimbursement completion remain unresolved."],known_unknowns:["The final recovery percentage for each affected asset is not established.","Long-term operation beyond the recovery-oriented bridge flow requires continued review."]});
Object.assign(get(events,"bir_ev_000008"),{source_count:2,confidence:"high",update_status:"current",description:"Nomad documented returned funds and a recovery process intended to make recovered assets available to affected users on a pro-rata basis.",reimbursement_status:"announced",notes:"The later restricted bridge relaunch is recorded separately."});
const addedEvents=[
{"id":"bir_ev_000048","bridge_id":"bir_bridge_000003","incident_id":"bir_inc_000003","event_type":"root_cause_analysis_published","event_date":"2022-08-05","event_date_precision":"day","title":"Nomad published root-cause analysis","description":"Nomad documented the initialization and message-verification flaw that allowed fraudulent messages to be accepted.","confidence":"high","record_maturity":"reviewed","update_status":"current","impact_level":"major","status_effect":"technical cause documented","source_count":1,"sort_order":15,"amount_text":null,"recovered_amount_text":null,"reimbursement_status":"unknown","restart_status":"paused","affected_chains":["ethereum","avalanche","unknown"],"affected_assets":["eth","usdc","usdt","wbtc"],"notes":null,"duplicate_of":null,"merged_into":null},
{"id":"bir_ev_000049","bridge_id":"bir_bridge_000003","incident_id":"bir_inc_000003","event_type":"recovery_bridge_relaunched","event_date":"2022-12-20","event_date_precision":"day","title":"Nomad recovery bridge relaunched with restrictions","description":"Affected users could bridge back madAssets and access pro-rata recovered funds, while new canonical-token deposits remained disabled.","confidence":"high","record_maturity":"reviewed","update_status":"current","impact_level":"major","status_effect":"limited recovery-oriented operation resumed","source_count":1,"sort_order":30,"amount_text":"approximately $1.2 million remained in the staging wallet","recovered_amount_text":"pro-rata recovered funds made accessible","reimbursement_status":"in_progress","restart_status":"partially_reopened","affected_chains":["ethereum","avalanche","unknown"],"affected_assets":["eth","usdc","usdt","wbtc"],"notes":"The relaunch did not restore unrestricted new deposits.","duplicate_of":null,"merged_into":null}
];
for(const x of addedEvents){if(events.some(v=>v.id===x.id))throw new Error(`duplicate ${x.id}`);events.push(x)}
const addedSources=[
{"id":"bir_src_000065","bridge_id":"bir_bridge_000003","incident_id":"bir_inc_000003","event_id":"bir_ev_000048","source_type":"postmortem","title":"Nomad Bridge Hack: Root Cause Analysis","url":"https://medium.com/nomad-xyz-blog/nomad-bridge-hack-root-cause-analysis-875ad2e5aacd","publisher":"Nomad","published_at":"2022-08-05","published_at_precision":"day","reliability":"high","source_tier":"tier_1","url_status":"live","accessed_at":"2026-06-15","claim_scope":"incident_case","language":"en","author":"Nomad","quote_excerpt":null,"is_primary":true,"is_paywalled":false,"is_official_domain":false,"supports_amount":false,"supports_recovery":false,"supports_reimbursement":false,"supports_reopen":false,"supports_shutdown":true,"supports_migration":false,"notes":"Primary technical root-cause analysis."},
{"id":"bir_src_000066","bridge_id":"bir_bridge_000003","incident_id":"bir_inc_000003","event_id":"bir_ev_000008","source_type":"official_blog","title":"The Road to Recovery","url":"https://medium.com/nomad-xyz-blog/the-road-to-recovery-6abe5eec8ff1","publisher":"Nomad","published_at":"2022-09-22","published_at_precision":"day","reliability":"high","source_tier":"tier_1","url_status":"live","accessed_at":"2026-06-15","claim_scope":"recovery","language":"en","author":"Nomad","quote_excerpt":null,"is_primary":true,"is_paywalled":false,"is_official_domain":false,"supports_amount":true,"supports_recovery":true,"supports_reimbursement":true,"supports_reopen":false,"supports_shutdown":false,"supports_migration":false,"notes":"Primary description of recovery and reimbursement planning."},
{"id":"bir_src_000067","bridge_id":"bir_bridge_000003","incident_id":"bir_inc_000003","event_id":"bir_ev_000049","source_type":"official_blog","title":"Nomad Bridge Relaunch Guide","url":"https://medium.com/nomad-xyz-blog/nomad-bridge-relaunch-guide-3a4ef6624f90","publisher":"Nomad","published_at":"2022-12-20","published_at_precision":"day","reliability":"high","source_tier":"tier_1","url_status":"live","accessed_at":"2026-06-15","claim_scope":"restart","language":"en","author":"Nomad","quote_excerpt":null,"is_primary":true,"is_paywalled":false,"is_official_domain":false,"supports_amount":true,"supports_recovery":true,"supports_reimbursement":true,"supports_reopen":true,"supports_shutdown":false,"supports_migration":true,"notes":"Primary source for the restricted recovery-oriented relaunch."}
];
for(const x of addedSources){if(evidence.some(v=>v.id===x.id))throw new Error(`duplicate ${x.id}`);evidence.push(x)}
write("bridges",bridges);write("incidents",incidents);write("events",events);write("evidence",evidence);
