from batch5_common import TODAY, event

EVENTS = [
    event(id="bir_ev_000104", bridge_id="bir_bridge_000023", event_type="protocol_launched", event_date="2020-05-27", event_date_precision="day", title="RenVM mainnet launched", description="Ren released RenVM Mainnet SubZero and RenBridge support for minting native assets such as BTC on Ethereum.", status_effect="protocol launched", affected_chains=["bitcoin", "ethereum"], affected_assets=["renbtc", "btc"], sort_order=10),
    event(id="bir_ev_000105", bridge_id="bir_bridge_000023", event_type="bridge_version_launched", event_date="2022-06-08", event_date_precision="day", title="RenBridge 3.0 launched", description="Ren announced RenBridge 3.0 with host-chain-to-host-chain asset transfers across supported networks.", status_effect="bridge capability expanded", affected_chains=["ethereum", "bnb-chain", "polygon", "avalanche", "unknown"], affected_assets=["renbtc", "unknown"], sort_order=20),
    event(id="bir_ev_000106", bridge_id="bir_bridge_000023", event_type="successor_plan_announced", event_date="2022-08-10", event_date_precision="day", title="Ren 2.0 announced", description="Ren introduced a planned community-run Ren 2.0 architecture and described future testnet, Chaosnet, and mainnet stages.", status_effect="planned successor announced", affected_chains=["unknown"], affected_assets=["unknown"], sort_order=30),
    event(id="bir_ev_000107", bridge_id="bir_bridge_000023", event_type="shutdown_announced", event_date="2022-11-18", event_date_precision="day", title="Ren 1.0 sunset announced after Alameda funding ended", description="Ren said the development team would lose Alameda-related funding after Q4 2022 and announced an accelerated Ren 1.0 sunset process.", impact_level="major", status_effect="shutdown planned", affected_chains=["bitcoin", "ethereum", "unknown"], affected_assets=["renbtc", "unknown"], sort_order=40),
    event(id="bir_ev_000108", bridge_id="bir_bridge_000023", event_type="minting_disabled_burn_window", event_date="2022-11-18", event_date_precision="day", title="Mint-disable and temporary burn-only transition announced", description="The sunset plan called for Ren 1.0 mints to be disabled while burns remained available for approximately thirty days before shutdown.", impact_level="major", status_effect="limited exit window announced", affected_chains=["bitcoin", "ethereum", "unknown"], affected_assets=["renbtc", "unknown"], sort_order=50),
    event(id="bir_ev_000109", bridge_id="bir_bridge_000023", event_type="current_terminal_state_verified", event_date=TODAY, event_date_precision="day", title="Ren 1.0 remained historical and Ren 2.0 remained coming soon", description="The current Ren Foundation page described Ren 1.0 as the historical network and Ren 2.0 as coming soon, without evidence of a public successor mainnet.", source_count=2, impact_level="major", status_effect="deprecated state verified", affected_chains=["unknown"], affected_assets=["unknown"], sort_order=60),

    event(id="bir_ev_000110", bridge_id="bir_bridge_000024", event_type="bridge_launched", event_date="2021-02-08", event_date_precision="day", title="Avalanche-Ethereum Bridge launched", description="Avalanche's first official Ethereum bridge entered production, connecting Ethereum assets with Avalanche C-Chain.", status_effect="bridge launched", affected_chains=["ethereum", "avalanche"], affected_assets=["weth", "usdc", "usdt", "dai", "wbtc"], sort_order=10),
    event(id="bir_ev_000111", bridge_id="bir_bridge_000024", event_type="replacement_announced", event_date="2021-07-08", event_date_precision="day", title="Next-generation replacement announced", description="Avalanche announced preparation for a faster, lower-cost successor bridge and planned migration of existing AEB assets.", status_effect="replacement pending", affected_chains=["ethereum", "avalanche"], affected_assets=["unknown"], sort_order=20),
    event(id="bir_ev_000112", bridge_id="bir_bridge_000024", event_type="bridge_replaced", event_date="2021-07-29", event_date_precision="day", title="Avalanche Bridge replaced AEB", description="The SGX-based Avalanche Bridge launched as the official replacement for the Avalanche-Ethereum Bridge.", impact_level="major", status_effect="migrated to successor", affected_chains=["ethereum", "avalanche"], affected_assets=["unknown"], sort_order=30),
    event(id="bir_ev_000113", bridge_id="bir_bridge_000024", event_type="legacy_bridge_sunset", event_date="2021-08", event_date_precision="month", title="AEB relayers and transfers were sunset", description="Official migration material described permanent disabling of AEB transfers, movement of held assets to the successor wallet, and token-upgrade support.", impact_level="major", status_effect="legacy bridge disabled", affected_chains=["ethereum", "avalanche"], affected_assets=["weth", "usdc", "usdt", "dai", "wbtc"], sort_order=40),
    event(id="bir_ev_000114", bridge_id="bir_bridge_000024", event_type="legacy_asset_upgrade_verified", event_date="2026-03-24", event_date_precision="day", title="Legacy AEB asset upgrade support remained available", description="Avalanche support documentation continued to explain how holders could swap deprecated AEB token contracts into current bridgeable assets.", status_effect="residual legacy support", affected_chains=["avalanche"], affected_assets=["unknown"], sort_order=50),

    event(id="bir_ev_000115", bridge_id="bir_bridge_000025", event_type="bridge_launched", event_date="2021-07-29", event_date_precision="day", title="Avalanche Bridge launched", description="Avalanche launched the new SGX-based bridge for transfers between Ethereum and Avalanche C-Chain.", status_effect="active successor launched", affected_chains=["ethereum", "avalanche"], affected_assets=["weth", "usdc", "usdt", "dai", "wbtc"], sort_order=10),
    event(id="bir_ev_000116", bridge_id="bir_bridge_000025", event_type="architecture_documented", event_date="2021-08-05", event_date_precision="day", title="SGX and Bridge Node architecture documented", description="Avalanche published a technical explanation of the SGX enclave, Bridge Nodes, threshold operation, and migration from AEB.", status_effect="successor architecture documented", affected_chains=["ethereum", "avalanche"], affected_assets=["unknown"], sort_order=20),
    event(id="bir_ev_000117", bridge_id="bir_bridge_000025", event_type="current_operation_verified", event_date=TODAY, event_date_precision="day", title="Avalanche Bridge remained operational through Core", description="Current Avalanche support documentation described active ETH and ERC-20 transfers between Ethereum and Avalanche C-Chain through the Core bridge interface.", status_effect="active operation verified", affected_chains=["ethereum", "avalanche"], affected_assets=["weth", "usdc", "usdt", "dai", "wbtc"], sort_order=30),

    event(id="bir_ev_000118", bridge_id="bir_bridge_000026", event_type="security_audit_completed", event_date="2020-12-18", event_date_precision="day", title="ShuttleFlow security audit announced", description="Conflux announced that PeckShield had completed a security audit of the ShuttleFlow cross-chain asset protocol.", status_effect="audited operation documented", affected_chains=["conflux-core-space", "ethereum", "unknown"], affected_assets=["cfx", "unknown"], sort_order=10),
    event(id="bir_ev_000119", bridge_id="bir_bridge_000026", event_type="multi_chain_operation_documented", event_date="2021-04-20", event_date_precision="day", title="ShuttleFlow multi-chain role documented", description="Conflux described ShuttleFlow as a transit-chain based multi-asset bridge connecting assets and infrastructure across DeFi networks.", status_effect="multi-chain operation documented", affected_chains=["conflux-core-space", "ethereum", "bnb-chain", "unknown"], affected_assets=["cfx", "eth", "usdt", "unknown"], sort_order=20),
    event(id="bir_ev_000120", bridge_id="bir_bridge_000026", event_type="frontend_upgrade_released", event_date="2021-07-29", event_date_precision="day", title="ShuttleFlow v1.3.0 frontend released", description="Conflux released a major ShuttleFlow frontend upgrade for cross-chain asset operations.", status_effect="interface upgraded", affected_chains=["conflux-core-space", "ethereum", "bnb-chain", "unknown"], affected_assets=["unknown"], sort_order=30),
    event(id="bir_ev_000121", bridge_id="bir_bridge_000026", event_type="migration_announced", event_date="2023-11-07", event_date_precision="day", title="ShuttleFlow closure and Zero Gravity migration announced", description="Conflux announced transfer of ShuttleFlow technology and bridge operations to Zero Gravity and provided a staged shutdown schedule.", source_count=2, impact_level="major", status_effect="migration announced", affected_chains=["conflux-core-space", "conflux-espace", "ethereum", "unknown"], affected_assets=["cfx", "unknown"], sort_order=40),
    event(id="bir_ev_000122", bridge_id="bir_bridge_000026", event_type="bridge_service_shutdown", event_date="2023-11-08", event_date_precision="day", title="ShuttleFlow bridge service ended", description="The announced bridge service end took effect and remaining users were directed to Zero Gravity, while a limited ShuttleFlow claim function remained available.", impact_level="major", status_effect="claim-only legacy mode", affected_chains=["conflux-core-space", "conflux-espace", "ethereum", "unknown"], affected_assets=["cfx", "unknown"], sort_order=50),
    event(id="bir_ev_000123", bridge_id="bir_bridge_000026", event_type="legacy_interface_shutdown", event_date="2024-01-06", event_date_precision="day", title="ShuttleFlow website and dApp shutdown date reached", description="The official transition schedule ended the residual ShuttleFlow website, dApp, and limited claim path after the migration period.", source_count=2, impact_level="major", status_effect="service fully ended", affected_chains=["conflux-core-space", "conflux-espace", "unknown"], affected_assets=["cfx", "unknown"], sort_order=60),
]
