from batch5_common import TODAY, evidence

EVIDENCE = [
    evidence(id="bir_src_000126", bridge_id="bir_bridge_000023", event_id="bir_ev_000104", source_type="official_blog", title="RenVM Mainnet Release", url="https://medium.com/renprotocol/renvm-mainnet-release-98cac4c6fa8e", publisher="Ren Protocol", published_at="2020-05-27", claim_scope="launch_date", author="Taiyang Zhang", notes="Official RenVM mainnet and RenBridge release announcement."),
    evidence(id="bir_src_000127", bridge_id="bir_bridge_000023", event_id="bir_ev_000105", source_type="official_blog", title="Introducing RenBridge 3.0", url="https://medium.com/renprotocol/introducing-renbridge-3-0-2b5f49aaf722", publisher="Ren Protocol", published_at="2022-06-08", claim_scope="bridge_version", author="Ren Community", notes="Official RenBridge 3.0 release announcement."),
    evidence(id="bir_src_000128", bridge_id="bir_bridge_000023", event_id="bir_ev_000106", source_type="official_blog", title="Introducing Ren 2.0", url="https://medium.com/renprotocol/introducing-ren-2-0-43025b3d5d6", publisher="Ren Protocol", published_at="2022-08-10", claim_scope="successor_plan", author="Ren Community", supports_migration=True, notes="Official plan describing future Ren 2.0 rollout stages rather than a completed mainnet launch."),
    evidence(id="bir_src_000129", bridge_id="bir_bridge_000023", event_id="bir_ev_000107", source_type="official_blog", title="Moving on from Alameda", url="https://medium.com/renprotocol/moving-on-from-alameda-da62a823ce93", publisher="Ren Protocol", published_at="2022-11-18", claim_scope="shutdown", author="Ren Community", supports_shutdown=True, supports_migration=True, notes="Primary source for funding termination and the Ren 1.0 sunset plan."),
    evidence(id="bir_src_000130", bridge_id="bir_bridge_000023", event_id="bir_ev_000108", source_type="official_blog", title="Moving on from Alameda - Ren 1.0 transition details", url="https://medium.com/renprotocol/moving-on-from-alameda-da62a823ce93", publisher="Ren Protocol", published_at="2022-11-18", claim_scope="terminal_timeline", author="Ren Community", supports_shutdown=True, notes="Same official notice, linked separately to the transition-window event."),
    evidence(id="bir_src_000131", bridge_id="bir_bridge_000023", event_id="bir_ev_000109", source_type="official_website", title="Ren Foundation", url="https://renprotocol.org/", publisher="Ren Foundation", published_at=TODAY, claim_scope="current_status", is_official_domain=True, supports_shutdown=True, supports_migration=True, notes="Current site labels Ren 1.0 as historical and Ren 2.0 as coming soon."),
    evidence(id="bir_src_000132", bridge_id="bir_bridge_000023", event_id="bir_ev_000109", source_type="official_repository", title="renproject GitHub organization", url="https://github.com/renproject", publisher="Ren project", published_at=TODAY, claim_scope="current_status", is_official_domain=True, notes="Official repository organization reviewed as current project context."),

    evidence(id="bir_src_000133", bridge_id="bir_bridge_000024", event_id="bir_ev_000110", source_type="official_blog", title="Introducing the Avalanche-Ethereum Light Bridge through CyberFi", url="https://medium.com/avalancheavax/introducing-the-avalanche-ethereum-light-bridge-aelb-through-the-cyberfi-asset-management-b280e830702f", publisher="Avalanche", published_at="2021-04-20", claim_scope="launch_date", notes="Official article states that AEB launched on February 8, 2021."),
    evidence(id="bir_src_000134", bridge_id="bir_bridge_000024", event_id="bir_ev_000111", source_type="official_blog", title="Preparing for the Next Generation Avalanche Bridge", url="https://medium.com/avalancheavax/preparing-for-the-next-generation-avalanche-bridge-ab-26f7521485e7", publisher="Avalanche", published_at="2021-07-08", claim_scope="migration", supports_migration=True, notes="Official preparation and migration announcement."),
    evidence(id="bir_src_000135", bridge_id="bir_bridge_000024", event_id="bir_ev_000112", source_type="official_blog", title="New Avalanche Bridge Builds on Intel SGX Technology", url="https://medium.com/avalancheavax/new-avalanche-bridge-builds-on-intel-sgx-technology-in-breakthrough-for-cross-chain-8f854e0e72e0", publisher="Avalanche", published_at="2021-07-29", claim_scope="migration", supports_migration=True, notes="Official launch statement explicitly describing Avalanche Bridge as the AEB replacement."),
    evidence(id="bir_src_000136", bridge_id="bir_bridge_000024", event_id="bir_ev_000113", source_type="official_blog", title="Avalanche Bridge: Secure Cross-Chain Asset Transfers Using Intel SGX", url="https://medium.com/avalancheavax/avalanche-bridge-secure-cross-chain-asset-transfers-using-intel-sgx-b04f5a4c7ad1", publisher="Avalanche", published_at="2021-08-05", claim_scope="terminal_timeline", supports_shutdown=True, supports_migration=True, notes="Official description of AEB relayer sunset, transfer disablement, and asset migration."),
    evidence(id="bir_src_000137", bridge_id="bir_bridge_000024", event_id="bir_ev_000114", source_type="official_support", title="How do I upgrade old Avalanche Bridge AEB assets?", url="https://support.avax.network/en/articles/6752048-how-do-i-upgrade-old-avalanche-bridge-aeb-assets", publisher="Avalanche Support", published_at="2026-03-24", claim_scope="legacy_support", is_official_domain=True, supports_migration=True, notes="Current official support for upgrading deprecated AEB token contracts."),
    evidence(id="bir_src_000138", bridge_id="bir_bridge_000025", event_id="bir_ev_000115", source_type="official_blog", title="New Avalanche Bridge Builds on Intel SGX Technology - launch", url="https://medium.com/avalancheavax/new-avalanche-bridge-builds-on-intel-sgx-technology-in-breakthrough-for-cross-chain-8f854e0e72e0", publisher="Avalanche", published_at="2021-07-29", claim_scope="launch_date", supports_migration=True, notes="Same official launch source, linked to the successor entity's launch event."),
    evidence(id="bir_src_000139", bridge_id="bir_bridge_000025", event_id="bir_ev_000116", source_type="official_blog", title="Avalanche Bridge: Secure Cross-Chain Asset Transfers Using Intel SGX", url="https://medium.com/avalancheavax/avalanche-bridge-secure-cross-chain-asset-transfers-using-intel-sgx-b04f5a4c7ad1", publisher="Avalanche", published_at="2021-08-05", claim_scope="entity_architecture", notes="Official SGX and Bridge Node architecture explanation."),
    evidence(id="bir_src_000140", bridge_id="bir_bridge_000025", event_id="bir_ev_000117", source_type="official_support", title="Avalanche Bridge FAQ", url="https://support.avax.network/en/articles/6092559-avalanche-bridge-faq", publisher="Avalanche Support", published_at="2026-01-28", claim_scope="current_status", is_official_domain=True, supports_reopen=True, notes="Current official documentation for active Ethereum and Avalanche C-Chain transfers through Core."),

    evidence(id="bir_src_000141", bridge_id="bir_bridge_000026", event_id="bir_ev_000118", source_type="official_blog", title="Conflux ShuttleFlow Protocol Passes PeckShield Security Audit", url="https://medium.com/conflux-network/shuttleflow-protocol-passes-peckshield-security-audit-fe0aa0f20d27", publisher="Conflux Network", published_at="2020-12-18", claim_scope="security_context", notes="Official audit announcement and protocol architecture context."),
    evidence(id="bir_src_000142", bridge_id="bir_bridge_000026", event_id="bir_ev_000119", source_type="official_blog", title="ShuttleFlow: Enabling the Future of DeFi through True Multi-Chain Connection", url="https://medium.com/conflux-network/shuttleflow-enabling-the-future-of-defi-through-true-multi-chain-connection-e60c2bada7d4", publisher="Conflux Network", published_at="2021-04-20", claim_scope="entity_architecture", notes="Official description of ShuttleFlow as a transit-chain based multi-chain bridge."),
    evidence(id="bir_src_000143", bridge_id="bir_bridge_000026", event_id="bir_ev_000120", source_type="official_blog", title="ShuttleFlow v1.3.0 Front End Upgrade Released", url="https://medium.com/conflux-network/shuttleflow-v1-3-0-front-end-upgrade-released-301b2ab59437", publisher="Conflux Network", published_at="2021-07-29", claim_scope="event", notes="Official frontend upgrade announcement."),
    evidence(id="bir_src_000144", bridge_id="bir_bridge_000026", event_id="bir_ev_000121", source_type="official_statement", title="ShuttleFlow is closing its services on 2023-11-08", url="https://forum.conflux.fun/t/announcement-shuttleflow-is-closing-its-services-on-2023-11-08-asset-bridging-operations-will-migrate-to-zero-gravity/19507", publisher="Conflux Foundation", published_at="2023-11-07", claim_scope="migration", is_official_domain=True, supports_shutdown=True, supports_migration=True, notes="Primary closure, technology handoff, and migration schedule."),
    evidence(id="bir_src_000145", bridge_id="bir_bridge_000026", event_id="bir_ev_000121", source_type="official_statement", title="ShuttleFlow to Zero Gravity transition schedule", url="https://forum.conflux.fun/t/announcement-shuttleflow-is-closing-its-services-on-2023-11-08-asset-bridging-operations-will-migrate-to-zero-gravity/19507", publisher="Conflux Foundation", published_at="2023-11-07", claim_scope="successor_context", is_official_domain=True, supports_migration=True, notes="Same official notice, linked separately to the successor-context claim."),
    evidence(id="bir_src_000146", bridge_id="bir_bridge_000026", event_id="bir_ev_000122", source_type="official_statement", title="ShuttleFlow bridge operation end schedule", url="https://forum.conflux.fun/t/announcement-shuttleflow-is-closing-its-services-on-2023-11-08-asset-bridging-operations-will-migrate-to-zero-gravity/19507", publisher="Conflux Foundation", published_at="2023-11-07", claim_scope="shutdown", is_official_domain=True, supports_shutdown=True, supports_migration=True, notes="Primary source for the November 8 bridge-operation end and claim-only period."),
    evidence(id="bir_src_000147", bridge_id="bir_bridge_000026", event_id="bir_ev_000123", source_type="official_statement", title="ShuttleFlow website and dApp final shutdown schedule", url="https://forum.conflux.fun/t/announcement-shuttleflow-is-closing-its-services-on-2023-11-08-asset-bridging-operations-will-migrate-to-zero-gravity/19507", publisher="Conflux Foundation", published_at="2023-11-07", claim_scope="shutdown", is_official_domain=True, supports_shutdown=True, notes="Primary source for the January 6, 2024 end of the residual claim interface."),
    evidence(id="bir_src_000148", bridge_id="bir_bridge_000026", event_id="bir_ev_000123", source_type="official_statement", title="KinetFlow Is Now Live", url="https://forum.conflux.fun/t/kinetflow-is-now-live/23143", publisher="Conflux Foundation", published_at="2025-11-25", claim_scope="successor_context", is_official_domain=True, supports_migration=True, notes="Later official lineage evidence: KinetFlow replaced Zero Gravity Portal and used ShuttleFlow and Zero Gravity technology."),
]
