import fs from 'node:fs';

const paths = {
  bridges: 'data/bridges.json',
  incidents: 'data/incidents.json',
  events: 'data/events.json',
  evidence: 'data/evidence.json',
};

const data = Object.fromEntries(Object.entries(paths).map(([k, p]) => [k, JSON.parse(fs.readFileSync(p, 'utf8'))]));

function fail(message) {
  throw new Error(`Batch 20 fail-closed: ${message}`);
}
function expectTail(list, id, label) {
  if (list.at(-1)?.id !== id) fail(`${label} tail expected ${id}, got ${list.at(-1)?.id}`);
}
function ensureFree(list, ids, label) {
  const existing = new Set(list.map((x) => x.id));
  for (const id of ids) if (existing.has(id)) fail(`${label} id already exists: ${id}`);
}
function ensureNoBridgeMatch(terms) {
  const haystack = data.bridges.map((b) => JSON.stringify(b).toLowerCase()).join('\n');
  for (const term of terms) if (haystack.includes(term.toLowerCase())) fail(`candidate bridge already appears canonical: ${term}`);
}

expectTail(data.bridges, 'bir_bridge_000072', 'bridge');
expectTail(data.incidents, 'bir_inc_000051', 'incident');
expectTail(data.events, 'bir_ev_000246', 'event');
expectTail(data.evidence, 'bir_src_000402', 'evidence');
ensureFree(data.bridges, ['bir_bridge_000073','bir_bridge_000074','bir_bridge_000075','bir_bridge_000076'], 'bridge');
ensureFree(data.incidents, ['bir_inc_000052','bir_inc_000053','bir_inc_000054','bir_inc_000055','bir_inc_000056'], 'incident');
ensureFree(data.events, Array.from({length:10}, (_,i)=>`bir_ev_${String(247+i).padStart(6,'0')}`), 'event');
ensureFree(data.evidence, Array.from({length:10}, (_,i)=>`bir_src_${String(403+i).padStart(6,'0')}`), 'evidence');
ensureNoBridgeMatch(['Alephium Bridge','Butter Bridge','Garden Finance','Gravity Bridge']);

const reviewed = '2026-09-01';

const bridges = [
  {
    id:'bir_bridge_000073', slug:'alephium-bridge', previous_slugs:[], redirect_from:[], canonical_name:'Alephium Bridge', type:'asset_bridge', status:'paused',
    summary:'Alephium Bridge is Alephium’s TokenBridge connecting Alephium with Ethereum and BNB Chain. On May 30, 2026, forged Wormhole-format events were accepted by the bridge guardian path, enabling redemption of forged VAAs against real collateral and minting of unbacked wALPH. The reviewed incident evidence establishes a bridge pause; later reopening is not established.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', last_reviewed_at:reviewed, last_verified_at:reviewed,
    aliases:['Alephium TokenBridge','TokenBridge'], launch_date:null, launch_date_precision:'unknown', end_date:null, end_date_precision:'unknown', terminal_reason:null,
    official_url:'https://docs.alephium.org/infrastructure/the-bridge/', official_domain:'docs.alephium.org', official_url_status:'live_verified', archived_url:null,
    primary_chains:['ethereum','bnb-chain','unknown'], primary_assets:['usdt','usdc','weth','wbtc','wbnb','unknown'], operator_name:'Alephium', operator_type:'protocol_team', ecosystem_name:'Alephium', related_protocols:['Wormhole TokenBridge fork'],
    brand_history_notes:null, major_incident_count:1, has_unresolved_incident:true, has_reimbursement_history:false, successor_id:null, predecessor_id:null, replacement_bridge_id:null, duplicate_of:null, merged_into:null,
    notes:'Alephium lacks a dedicated BIR chain-reference key, so the Alephium side and wALPH are conservatively represented with unknown references. The June 2 burn of unbacked wALPH is not treated as recovery of the real collateral drained on Ethereum/BNB Chain.'
  },
  {
    id:'bir_bridge_000074', slug:'butter-bridge-v3-1', previous_slugs:[], redirect_from:[], canonical_name:'Butter Bridge V3.1', type:'asset_bridge', status:'limited',
    summary:'Butter Bridge V3.1 provided the MAPO cross-chain service between legacy ERC-20 MAPO and MAP Protocol mainnet MAPO. On May 20, 2026, the OmniServiceProxy path was exploited to mint unauthorized MAPO on Ethereum and BNB Chain. MAP Protocol states that mainnet consensus, native MAPO, light-client verification, Oracle multisig, and project-team keys were unaffected; the affected service was suspended and remediation followed.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', last_reviewed_at:reviewed, last_verified_at:reviewed,
    aliases:['MAPO Butter Bridge','Butter Network Bridge V3.1'], launch_date:null, launch_date_precision:'unknown', end_date:null, end_date_precision:'unknown', terminal_reason:null,
    official_url:'https://medium.com/mapprotocol/map-protocol-may-updates-5003b0fc5d8f', official_domain:'medium.com', official_url_status:'live_verified', archived_url:null,
    primary_chains:['ethereum','bnb-chain','unknown'], primary_assets:['unknown'], operator_name:'Butter Network / MAP Protocol ecosystem', operator_type:'ecosystem', ecosystem_name:'MAP Protocol', related_protocols:['MAP Protocol','Butter Network','OmniServiceProxy'],
    brand_history_notes:'This record is scoped to the affected Butter Bridge V3.1 cross-chain service and does not represent MAP Protocol mainnet as compromised.', major_incident_count:1, has_unresolved_incident:true, has_reimbursement_history:true, successor_id:null, predecessor_id:null, replacement_bridge_id:null, duplicate_of:null, merged_into:null,
    notes:'MAPO has no dedicated BIR asset-reference key and MAP Protocol has no dedicated chain key, so those references remain unknown. A later audited-contract deployment and compensation framework are recorded without inferring completed reimbursement or unrestricted bridge reopening.'
  },
  {
    id:'bir_bridge_000075', slug:'garden-finance', previous_slugs:[], redirect_from:[], canonical_name:'Garden Finance', type:'interoperability_protocol', status:'limited',
    summary:'Garden Finance is a cross-chain atomic-swap protocol using HTLCs and independent solvers. Two separate solver-layer security incidents are recorded: an October 2025 compromise of a solver operating environment and a July 2026 compromise of an independent solver’s off-chain database. Garden states that protocol contracts and user funds were not compromised in either incident.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', last_reviewed_at:reviewed, last_verified_at:reviewed,
    aliases:['Garden','Garden Protocol'], launch_date:null, launch_date_precision:'unknown', end_date:null, end_date_precision:'unknown', terminal_reason:null,
    official_url:'https://garden.finance/', official_domain:'garden.finance', official_url_status:'live_verified', archived_url:null,
    primary_chains:['bitcoin','ethereum','base','arbitrum','bnb-chain','unknown'], primary_assets:['usdt','usdc','wbtc','eth','unknown'], operator_name:'Garden Finance', operator_type:'protocol_team', ecosystem_name:'Garden', related_protocols:['Garden HTLC','Garden solvers'],
    brand_history_notes:null, major_incident_count:2, has_unresolved_incident:true, has_reimbursement_history:false, successor_id:null, predecessor_id:null, replacement_bridge_id:null, duplicate_of:null, merged_into:null,
    notes:'Both incidents are scoped to solver infrastructure. Solver-owned losses are not converted into user-loss or protocol-contract-compromise claims. Latest unrestricted service restoration after the July 2026 pause is not established in the admitted incident evidence.'
  },
  {
    id:'bir_bridge_000076', slug:'gravity-bridge', previous_slugs:[], redirect_from:[], canonical_name:'Gravity Bridge', type:'asset_bridge', status:'paused',
    summary:'Gravity Bridge connects Ethereum assets with the Cosmos ecosystem. On May 30, 2026, approximately $5.4 million in assets were reported drained and the Gravity team instructed validators to halt validators and orchestrators while the incident was investigated. Public technical analyses disagree on the exact mechanism, so BIR keeps the attack vector unknown pending authoritative resolution.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', last_reviewed_at:reviewed, last_verified_at:reviewed,
    aliases:['Gravity'], launch_date:null, launch_date_precision:'unknown', end_date:null, end_date_precision:'unknown', terminal_reason:null,
    official_url:'https://www.gravitybridge.net/', official_domain:'gravitybridge.net', official_url_status:'live_unverified', archived_url:null,
    primary_chains:['ethereum','cosmos-interchain'], primary_assets:['usdc','weth','usdt','unknown'], operator_name:'Gravity Bridge', operator_type:'protocol_team', ecosystem_name:'Cosmos interchain', related_protocols:['Cosmos'],
    brand_history_notes:null, major_incident_count:1, has_unresolved_incident:true, has_reimbursement_history:false, successor_id:null, predecessor_id:null, replacement_bridge_id:null, duplicate_of:null, merged_into:null,
    notes:'PAXG is conservatively represented as unknown because BIR has no dedicated PAXG asset key. The bridge halt is first-party acknowledged through contemporaneous reporting; no authoritative postmortem resolving the disputed mechanism was located.'
  }
];

const incidents = [
  {
    id:'bir_inc_000052', bridge_id:'bir_bridge_000073', slug:'alephium-bridge-2026-forged-vaa-exploit', previous_slugs:[], redirect_from:[], title:'Alephium Bridge 2026 forged-message exploit', incident_date:'2026-05-30', incident_date_precision:'day', incident_type:'exploit',
    summary:'An attacker deployed a fake-event contract on Alephium that emitted forged Wormhole-format messages. The bridge guardian path signed the resulting VAAs, which were redeemed on Ethereum and BNB Chain to release real collateral and mint unbacked wALPH. Alephium later burned 13,257,077.37295 unbacked wALPH, while 500,000 wALPH had escaped before the pause.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', source_count:2, last_reviewed_at:reviewed, last_verified_at:reviewed, is_major_incident:true,
    reported_loss_usd_display:'about $815,000', reported_loss_usd:815000, reported_loss_usd_min:null, reported_loss_usd_max:null,
    reported_loss_text:'Independent technical reporting estimates approximately $815,000 of bridge collateral drained; Alephium’s first-party report separately enumerates the forged-message flow and unbacked wALPH mint/burn quantities.',
    reported_loss_assets:['usdt','usdc','weth','wbtc','wbnb','unknown'], usd_valuation_date:'2026-05-30', loss_amount_basis:'mixed_sources', amount_confidence:'medium',
    amount_note:'The USD total is secondary corroboration. The authorized burn of unbacked wALPH is not subtracted from the real-collateral loss figure.', amount_claims:[{amount_text:'bridge collateral drained',amount_usd_text:'about $815,000',source_id:'bir_src_000404',basis:'reported_by_security_firm',usd_valuation_date:'2026-05-30',notes:'Secondary technical valuation; first-party report is authoritative for mechanics and token quantities.'}],
    recovery_status:'none', reimbursement_status:'unknown', restart_status:'paused', current_outcome:'paused_long_term', is_unresolved:true,
    unresolved_reason:['Recovery of the drained real collateral is not established.','Completed reimbursement is not established.','A dated bridge reopening is not established.'],
    affected_chains:['ethereum','bnb-chain','unknown'], affected_assets:['usdt','usdc','weth','wbtc','wbnb','unknown'], attack_vector_category:'message_verification_failure', postmortem_available:'unclear',
    known_unknowns:['Alephium explicitly states that its June 2 on-chain report is not the full postmortem.','The final recovery and reimbursement outcome remains unresolved.'], conflicting_claims:[], duplicate_of:null, merged_into:null, split_from:null, split_reason:null
  },
  {
    id:'bir_inc_000053', bridge_id:'bir_bridge_000074', slug:'butter-bridge-v3-1-2026-unauthorized-mapo-mint', previous_slugs:[], redirect_from:[], title:'Butter Bridge V3.1 2026 unauthorized MAPO mint exploit', incident_date:'2026-05-20', incident_date_precision:'day', incident_type:'exploit',
    summary:'A flaw in Butter Bridge V3.1’s OmniServiceProxy cross-chain retry path was exploited, resulting in unauthorized MAPO minting on Ethereum and BNB Chain. MAP Protocol states that the flaw was isolated to the affected Butter Bridge path and did not compromise MAP mainnet consensus, native MAPO, light-client verification, Oracle multisig, or project-team keys.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', source_count:2, last_reviewed_at:reviewed, last_verified_at:reviewed, is_major_incident:true,
    reported_loss_usd_display:'about $180,000 extracted liquidity', reported_loss_usd:180000, reported_loss_usd_min:null, reported_loss_usd_max:null,
    reported_loss_text:'Security reporting estimates roughly $180,000 of liquidity was extracted after the unauthorized mint. The enormous notional quantity of unauthorized MAPO minted is not treated as equivalent to realized USD loss.',
    reported_loss_assets:['unknown'], usd_valuation_date:'2026-05-20', loss_amount_basis:'reported_by_security_firm', amount_confidence:'medium',
    amount_note:'Keep unauthorized minted quantity, realized liquidity extraction, and compensation scope separate.', amount_claims:[{amount_text:'realized liquidity extraction after unauthorized MAPO mint',amount_usd_text:'about $180,000',source_id:'bir_src_000406',basis:'reported_by_security_firm',usd_valuation_date:'2026-05-20',notes:'Secondary security-firm estimate; notional unauthorized MAPO supply is not a USD loss proxy.'}],
    recovery_status:'unknown', reimbursement_status:'announced', restart_status:'unknown', current_outcome:'limited_after_incident', is_unresolved:true,
    unresolved_reason:['Final attacker-fund recovery is not established.','MAP Protocol announced a Foundation-funded protection and compensation framework, but completion is not established.','Deployment of new audited contracts does not by itself establish unrestricted reopening of the affected V3.1 service.'],
    affected_chains:['ethereum','bnb-chain','unknown'], affected_assets:['unknown'], attack_vector_category:'smart_contract_bug', postmortem_available:'unclear',
    known_unknowns:['Final realized loss beyond the independently reported liquidity extraction is not normalized.','Final reimbursement and restart outcomes remain unresolved.'], conflicting_claims:[], duplicate_of:null, merged_into:null, split_from:null, split_reason:null
  },
  {
    id:'bir_inc_000054', bridge_id:'bir_bridge_000075', slug:'garden-finance-2025-solver-infrastructure-compromise', previous_slugs:[], redirect_from:[], title:'Garden Finance 2025 solver infrastructure compromise', incident_date:'2025-10-30', incident_date_precision:'day', incident_type:'hack',
    summary:'An attacker gained unauthorized access to an independent Garden solver’s operating environment and drained approximately $11.4 million in crypto assets belonging to the solver across multiple chains. Garden’s later forensic report states that protocol contracts were not compromised and no user funds were at risk.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', source_count:2, last_reviewed_at:reviewed, last_verified_at:reviewed, is_major_incident:true,
    reported_loss_usd_display:'about $11.4 million', reported_loss_usd:11400000, reported_loss_usd_min:null, reported_loss_usd_max:null,
    reported_loss_text:'Garden reports approximately $11.4 million in crypto assets belonging to the independent solver were drained across multiple chains.', reported_loss_assets:['wbtc','usdc','usdt','eth','unknown'], usd_valuation_date:'2025-10-30', loss_amount_basis:'reported_by_project', amount_confidence:'high',
    amount_note:'This is a solver-owned asset loss, not a user-fund loss or Garden protocol-contract loss.', amount_claims:[{amount_text:'solver-owned crypto assets drained across multiple chains',amount_usd_text:'approximately $11.4 million',source_id:'bir_src_000407',basis:'reported_by_project',usd_valuation_date:'2025-10-30',notes:'Garden first-party incident report.'}],
    recovery_status:'none', reimbursement_status:'not_applicable', restart_status:'reopened', current_outcome:'active_after_incident', is_unresolved:true,
    unresolved_reason:['Garden states that recovery efforts continued, but completed recovery of the drained solver-owned assets is not established.'], affected_chains:['ethereum','arbitrum','unknown'], affected_assets:['wbtc','usdc','usdt','eth','unknown'], attack_vector_category:'operator_or_governance_issue', postmortem_available:'available',
    known_unknowns:['The exact initial compromise method remains not fully established by the admitted first-party source.','Attribution indicators are not treated as a legal attribution finding.'], conflicting_claims:[], duplicate_of:null, merged_into:null, split_from:null, split_reason:null
  },
  {
    id:'bir_inc_000055', bridge_id:'bir_bridge_000075', slug:'garden-finance-2026-solver-database-compromise', previous_slugs:[], redirect_from:[], title:'Garden Finance 2026 solver database compromise', incident_date:'2026-07-26', incident_date_precision:'day', incident_type:'hack',
    summary:'Garden stated that an independent solver’s off-chain database was compromised and fraudulent swap records were inserted, causing the solver to release funds for swaps that had not been funded by counterparties. Garden said neither its protocol nor HTLC smart contracts were compromised and no user funds were lost or placed at risk; the app was taken offline during containment.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', source_count:2, last_reviewed_at:reviewed, last_verified_at:reviewed, is_major_incident:true,
    reported_loss_usd_display:'about $450,000 reported', reported_loss_usd:450000, reported_loss_usd_min:null, reported_loss_usd_max:null,
    reported_loss_text:'Blockaid/secondary reporting estimated about $450,000 in USDT drained from solver-owned settlement funds across Ethereum, Base, Arbitrum, and BNB Chain; Garden said it was still confirming the exact amount, assets, and networks.', reported_loss_assets:['usdt'], usd_valuation_date:'2026-07-26', loss_amount_basis:'reported_by_security_firm', amount_confidence:'medium',
    amount_note:'The approximately $450,000 figure remains an external estimate because Garden had not finalized the exact amount at the reviewed update.', amount_claims:[{amount_text:'solver-owned USDT drained',amount_usd_text:'about $450,000',source_id:'bir_src_000410',basis:'reported_by_security_firm',usd_valuation_date:'2026-07-26',notes:'External estimate; Garden said final amount/assets/networks were still being confirmed.'}],
    recovery_status:'unknown', reimbursement_status:'not_applicable', restart_status:'paused', current_outcome:'limited_after_incident', is_unresolved:true,
    unresolved_reason:['Final loss amount and asset/network reconciliation were still being confirmed.','Completed attacker-fund recovery is not established.','A dated unrestricted service reopening is not established in the admitted evidence.'], affected_chains:['ethereum','base','arbitrum','bnb-chain'], affected_assets:['usdt'], attack_vector_category:'operator_or_governance_issue', postmortem_available:'not_found',
    known_unknowns:['Exact final solver-owned loss remains unconfirmed by Garden.','The database compromise is not a smart-contract exploit and is not generalized into compromise of Garden HTLC contracts.'], conflicting_claims:[], duplicate_of:null, merged_into:null, split_from:null, split_reason:null
  },
  {
    id:'bir_inc_000056', bridge_id:'bir_bridge_000076', slug:'gravity-bridge-2026-drain', previous_slugs:[], redirect_from:[], title:'Gravity Bridge 2026 drain and emergency halt', incident_date:'2026-05-30', incident_date_precision:'day', incident_type:'exploit',
    summary:'Gravity Bridge was drained of approximately $5.4 million in USDC, WETH, USDT and PAXG-equivalent assets. The Gravity team acknowledged an incident and instructed validators to halt validators and orchestrators while the investigation continued. Because public technical analyses disagree on the exact mechanism and no authoritative first-party postmortem was located, the canonical attack vector remains unknown.',
    confidence:'high', record_maturity:'reviewed', update_status:'current', source_count:2, last_reviewed_at:reviewed, last_verified_at:reviewed, is_major_incident:true,
    reported_loss_usd_display:'about $5.4 million', reported_loss_usd:5400000, reported_loss_usd_min:null, reported_loss_usd_max:null,
    reported_loss_text:'Independent on-chain/security reporting estimated approximately $5.4 million drained, including USDC, WETH, USDT and PAXG.', reported_loss_assets:['usdc','weth','usdt','unknown'], usd_valuation_date:'2026-05-30', loss_amount_basis:'mixed_sources', amount_confidence:'medium',
    amount_note:'The approximate aggregate is secondary. PAXG uses the unknown asset reference because BIR lacks a PAXG key.', amount_claims:[{amount_text:'USDC, WETH, USDT and PAXG drained',amount_usd_text:'about $5.4 million',source_id:'bir_src_000412',basis:'reported_by_news',usd_valuation_date:'2026-05-30',notes:'Contemporaneous reporting based on on-chain security researchers.'}],
    recovery_status:'unknown', reimbursement_status:'unknown', restart_status:'paused', current_outcome:'paused_long_term', is_unresolved:true,
    unresolved_reason:['Final attacker-fund recovery is not established.','Reimbursement is not established.','A dated bridge reopening is not established.','The attack mechanism remains materially disputed in public technical analyses.'], affected_chains:['ethereum','cosmos-interchain'], affected_assets:['usdc','weth','usdt','unknown'], attack_vector_category:'unknown', postmortem_available:'not_found',
    known_unknowns:['Suspected signing-key compromise and denom-mapping poisoning are competing public explanations and neither is promoted as canonical without authoritative resolution.','Final recovery, reimbursement and restart outcomes remain unknown.'], conflicting_claims:[{claim:'attack_vector_category',values:['validator_key_compromise','message_verification_failure'],source_ids:['bir_src_000412'],resolution:'kept_unknown_pending_authoritative_postmortem'}], duplicate_of:null, merged_into:null, split_from:null, split_reason:null
  }
];

const baseEvent = (id, bridge_id, incident_id, event_type, event_date, title, description, impact_level, status_effect, sort_order, affected_assets, notes, source_count=1) => ({
  id, bridge_id, incident_id, confidence:'high', record_maturity:'reviewed', update_status:'current', impact_level, status_effect, sort_order,
  amount_text:null, recovered_amount_text:null, reimbursement_status:'not_applicable', restart_status:'not_applicable', affected_assets, notes, duplicate_of:null, merged_into:null,
  event_type, event_date, event_date_precision:'day', title, description, source_count,
  affected_chains: bridge_id==='bir_bridge_000073'?['ethereum','bnb-chain','unknown']:bridge_id==='bir_bridge_000074'?['ethereum','bnb-chain','unknown']:bridge_id==='bir_bridge_000075'?['ethereum','arbitrum','base','bnb-chain','unknown']:['ethereum','cosmos-interchain']
});

const events = [
  baseEvent('bir_ev_000247','bir_bridge_000073','bir_inc_000052','exploit_occurred','2026-05-30','Alephium TokenBridge forged-message exploit','Forged Wormhole-format events produced guardian-signed VAAs that were redeemed against real bridge collateral and used to mint unbacked wALPH.','critical','paused',10,['usdt','usdc','weth','wbtc','wbnb','unknown'],'First-party Alephium report establishes the forged-event/VAA sequence; USD loss is kept in the incident record.',2),
  baseEvent('bir_ev_000248','bir_bridge_000073','bir_inc_000052','funds_recovered','2026-06-02','Alephium burns most unbacked wALPH','Alephium reported an authorized burn of 13,257,077.37295 unbacked wALPH, 96.4% of the forged-mint total; 500,000 wALPH had escaped before the pause.','high','paused',20,['unknown'],'This is cleanup of unbacked supply, not recovery of drained real collateral.',1),
  baseEvent('bir_ev_000249','bir_bridge_000074','bir_inc_000053','exploit_occurred','2026-05-20','Butter Bridge V3.1 unauthorized MAPO mint','The affected OmniServiceProxy cross-chain path was manipulated, resulting in unauthorized MAPO minting on Ethereum and BNB Chain.','high','paused',10,['unknown'],'MAP mainnet consensus and the other explicitly excluded core components are not marked compromised.',2),
  baseEvent('bir_ev_000250','bir_bridge_000074','bir_inc_000053','bridge_paused','2026-05-20','Butter cross-chain service suspended for remediation','MAP Protocol reported that the affected Butter cross-chain service was suspended while containment, tracing, audited-contract deployment and user-protection work proceeded.','high','limited',20,['unknown'],'Later audited-contract deployment does not automatically establish full unrestricted reopening.',1),
  baseEvent('bir_ev_000251','bir_bridge_000075','bir_inc_000054','hack_disclosed','2025-10-30','Garden solver operating environment compromised','Unauthorized access to an independent solver operating environment led to approximately $11.4 million in solver-owned crypto assets being drained across multiple chains.','critical','limited',10,['wbtc','usdc','usdt','eth','unknown'],'Garden states protocol contracts and user funds were unaffected.',2),
  baseEvent('bir_ev_000252','bir_bridge_000075','bir_inc_000054','bridge_paused','2025-10-30','Garden pauses user-facing services during 2025 response','Garden activated incident response and paused user-facing services as a precaution while isolating and investigating the solver compromise.','high','paused',20,['unknown'],'The pause is precautionary response evidence and does not imply protocol-contract compromise.',1),
  baseEvent('bir_ev_000253','bir_bridge_000075','bir_inc_000055','hack_disclosed','2026-07-26','Garden independent-solver database compromised','An independent solver’s off-chain database was compromised and fraudulent swap records caused solver-owned settlement funds to be released for unfunded swaps.','high','limited',10,['usdt'],'Garden states the protocol and HTLC contracts were not compromised and user funds were not at risk.',2),
  baseEvent('bir_ev_000254','bir_bridge_000075','bir_inc_000055','bridge_paused','2026-07-26','Garden app taken offline during July 2026 containment','Garden took the app offline while the affected solver infrastructure was isolated and reviewed with security partners.','high','paused',20,['usdt'],'No unrestricted reopening date is inferred from later website reachability.',1),
  baseEvent('bir_ev_000255','bir_bridge_000076','bir_inc_000056','exploit_occurred','2026-05-30','Gravity Bridge drained','Independent security and media reporting identified approximately $5.4 million of assets drained from Gravity Bridge.','critical','paused',10,['usdc','weth','usdt','unknown'],'Attack vector remains unknown in canonical data because technical explanations conflict.',2),
  baseEvent('bir_ev_000256','bir_bridge_000076','bir_inc_000056','bridge_paused','2026-05-30','Gravity validators and orchestrators instructed to halt','The Gravity team acknowledged an incident and instructed validators to halt validators and orchestrators while investigation continued; reporting subsequently described the bridge as halted.','high','paused',20,['unknown'],'First-party acknowledgement is preserved without promoting a disputed root-cause claim.',2)
];

const evidence = [
  {id:'bir_src_000403',bridge_id:'bir_bridge_000073',incident_id:'bir_inc_000052',event_id:'bir_ev_000247',source_type:'official_blog',title:'The Alephium Bridge Exploit: On-Chain Report',url:'https://alephium.org/news/post/the-alephium-bridge-exploit-on-chain-report/',publisher:'Alephium',published_at:'2026-06-02',published_at_precision:'day',reliability:'high',source_tier:'tier_1',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'incident_case',language:'en',author:null,quote_excerpt:null,is_primary:true,is_paywalled:false,is_official_domain:true,supports_amount:true,supports_recovery:true,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'First-party on-chain report establishing the May 30 forged-event/VAA sequence, real-collateral redemption, unbacked wALPH mint, and June 2 authorized burn. The publisher explicitly says this report is not the full postmortem.'},
  {id:'bir_src_000404',bridge_id:'bir_bridge_000073',incident_id:'bir_inc_000052',event_id:'bir_ev_000247',source_type:'security_firm_report',title:'The Alephium TokenBridge Exploit ($815K) — Lemma Critical Brief No.023',url:'https://lemma.frame00.com/critical/briefs/023-alephium-tokenbridge/',publisher:'Lemma Critical',published_at:'2026-06-05',published_at_precision:'day',reliability:'medium',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'amount',language:'en',author:null,quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:true,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'Independent technical corroboration for the approximately $815K collateral-loss estimate and forged-message mechanism. First-party Alephium evidence remains authoritative where claims differ.'},
  {id:'bir_src_000405',bridge_id:'bir_bridge_000074',incident_id:'bir_inc_000053',event_id:'bir_ev_000249',source_type:'official_blog',title:'MAP Protocol May Updates',url:'https://medium.com/mapprotocol/map-protocol-may-updates-5003b0fc5d8f',publisher:'MAP Protocol',published_at:'2026-06-04',published_at_precision:'day',reliability:'high',source_tier:'tier_1',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'incident_case',language:'en',author:'MAP Protocol',quote_excerpt:null,is_primary:true,is_paywalled:false,is_official_domain:false,supports_amount:false,supports_recovery:false,supports_reimbursement:true,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'First-party MAP Protocol update establishing the Butter Bridge V3.1 incident, affected OmniServiceProxy path, explicit exclusions for MAP core infrastructure, service suspension, audited-contract deployment, snapshot mapping and Foundation-funded user-protection framework.'},
  {id:'bir_src_000406',bridge_id:'bir_bridge_000074',incident_id:'bir_inc_000053',event_id:'bir_ev_000249',source_type:'security_firm_report',title:'SlowMist Hacked — Butter Bridge',url:'https://hacked.slowmist.io/?c=Bridge&page=1',publisher:'SlowMist',published_at:'2026-05-20',published_at_precision:'day',reliability:'high',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'amount',language:'en',author:null,quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:false,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'Security-firm database corroboration for the Butter Bridge V3.1 exploit and approximately $180K realized liquidity extraction. The notional unauthorized MAPO mint is not treated as realized USD loss.'},
  {id:'bir_src_000407',bridge_id:'bir_bridge_000075',incident_id:'bir_inc_000054',event_id:'bir_ev_000251',source_type:'postmortem',title:'Garden Incident Report — October 30, 2025',url:'https://garden.finance/blog/garden-incident-report-october-30-2025',publisher:'Garden Finance',published_at:'2026-01-28',published_at_precision:'day',reliability:'high',source_tier:'tier_1',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'incident_case',language:'en',author:null,quote_excerpt:null,is_primary:true,is_paywalled:false,is_official_domain:true,supports_amount:true,supports_recovery:true,supports_reimbursement:false,supports_reopen:true,supports_shutdown:true,supports_migration:false,notes:'First-party incident report establishing October 30, 2025 solver-environment compromise, approximately $11.4M solver-owned loss, protocol/user-fund exclusion, response pause and continuing recovery efforts.'},
  {id:'bir_src_000408',bridge_id:'bir_bridge_000075',incident_id:'bir_inc_000054',event_id:'bir_ev_000251',source_type:'news_article',title:'Garden Finance shares forensic findings: Security breach limited to solver layer',url:'https://www.theblock.co/amp/post/387636/garden-finance-shares-forensic-findings-security-breach-limited-to-solver-layer',publisher:'The Block',published_at:'2026-01-29',published_at_precision:'day',reliability:'high',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'incident_case',language:'en',author:'Karla Vallecillo',quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:false,supports_reimbursement:false,supports_reopen:false,supports_shutdown:false,supports_migration:false,notes:'Corroborates the approximately $11.4M solver-owned loss and reports Garden/EY forensic findings that the breach was limited to solver infrastructure.'},
  {id:'bir_src_000409',bridge_id:'bir_bridge_000075',incident_id:'bir_inc_000055',event_id:'bir_ev_000253',source_type:'news_article',title:'Garden Finance Says Solver Breach Caused $450K Drain',url:'https://cointelegraph.com/news/garden-finance-app-offline-450k-htlc-exploit',publisher:'Cointelegraph',published_at:'2026-07-27',published_at_precision:'day',reliability:'high',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'incident_case',language:'en',author:'Ezra Reguerra',quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:false,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'Updated article incorporates direct Garden Finance spokesperson clarification: independent solver database compromise, fraudulent swap records, protocol/HTLC contracts unaffected, no user funds at risk, app temporarily offline.'},
  {id:'bir_src_000410',bridge_id:'bir_bridge_000075',incident_id:'bir_inc_000055',event_id:'bir_ev_000253',source_type:'security_firm_report',title:'SlowMist Hacked — Garden Finance',url:'https://hacked.slowmist.io/?c=&page=2',publisher:'SlowMist',published_at:'2026-07-26',published_at_precision:'day',reliability:'high',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'amount',language:'en',author:null,quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:false,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'Security-firm database corroboration for the approximately $450K USDT estimate and Garden’s solver-database explanation. Garden had not yet finalized exact amount/assets/networks.'},
  {id:'bir_src_000411',bridge_id:'bir_bridge_000076',incident_id:'bir_inc_000056',event_id:'bir_ev_000256',source_type:'news_article',title:'Gravity Bridge Protocol Loses $5.4 Million in Hack Attack',url:'https://incrypted.com/en/gravity-bridge-protocol-loses-5-4-million-hack-attack/',publisher:'Incrypted',published_at:'2026-05-31',published_at_precision:'day',reliability:'medium',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'event',language:'en',author:'Nazar Pyrih',quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:false,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'Preserves the contemporaneous first-party Gravity statement instructing validators to halt validators and orchestrators while investigation continued; not used to resolve the disputed technical mechanism.'},
  {id:'bir_src_000412',bridge_id:'bir_bridge_000076',incident_id:'bir_inc_000056',event_id:'bir_ev_000255',source_type:'news_article',title:'Cosmos-based Gravity Bridge drained of $5.4 million in suspected key compromise, researchers say',url:'https://www.theblock.co/news/ecosystems/2026-05-30-cosmos-based-gravity-bridge-drained-of-5-4-million-in-suspected-key-compromise-researchers-say-403108',publisher:'The Block',published_at:'2026-05-30',published_at_precision:'day',reliability:'high',source_tier:'tier_2',url_status:'live',archived_url:null,accessed_at:reviewed,claim_scope:'amount',language:'en',author:'Zack Abrams',quote_excerpt:null,is_primary:false,is_paywalled:false,is_official_domain:false,supports_amount:true,supports_recovery:false,supports_reimbursement:false,supports_reopen:false,supports_shutdown:true,supports_migration:false,notes:'Contemporaneous corroboration for the approximately $5.4M drain and asset breakdown. Its suspected signing-key mechanism is not promoted because later technical analyses materially disagree.'}
];

data.bridges.push(...bridges);
data.incidents.push(...incidents);
data.events.push(...events);
data.evidence.push(...evidence);

for (const [key, p] of Object.entries(paths)) fs.writeFileSync(p, `${JSON.stringify(data[key], null, 2)}\n`);
console.log(`Batch 20 applied: +${bridges.length} bridges, +${incidents.length} incidents, +${events.length} events, +${evidence.length} evidence`);
